Update unix build.yml

diff --git a/.github/workflows/unix build.yml b/.github/workflows/unix build.yml
--- a/.github/workflows/unix build.yml
+++ b/.github/workflows/unix build.yml
@@ -30,7 +30,26 @@ jobs:
       - name: build
         run: |
              cd ..
-             git clone https://github.com/catchorg/Catch2.git
              cd Wisteria-Dataviz
              cmake ./
              make -j4
+             
+      - name: run tests
+        run: |
+             git clone https://github.com/catchorg/Catch2.git
+             cd Wisteria-Dataviz/tests
+             cmake ./
+             make -j4
+             cd bin
+             ./WisteriaTestRunner --reporter JUnit::out=WDV-junit.xml
+             cat WDV-junit.xml
+             errors=$(cat WDV-junit.xml | grep -Po '(errors)="\K[^"]*')
+             failures=$(cat WDV-junit.xml | grep -Po '(failures)="\K[^"]*')
+             echo "Error count is: ${errors}"
+             echo "Failure count is: ${failures}"
+             if [ "$errors" -gt 0 ]; then
+               exit 1
+             fi
+             if [ "$failures" -gt 0 ]; then
+               exit 1
+             fi
